spring:
  data:
    mongodb:
      uri: mongodb+srv://bootcamp:eo4IaJNIbjk4f8ls@cluster0.hlzdcri.mongodb.net/bankingBusiness?retryWrites=true&w=majority
  cloud:
    config:
      server:
        git:
          default-label: master
          uri: https://github.com/jhonatan-maza/bootcamp-customer
  application:
    name: bootcamp-customer
    
eureka:
  client:
    fetch-registry: 'true
    register-with-eureka: true
  instance:
    instance-id: :${spring.application.name}:${spring.application.instance_id:${random.value}}
    service-url:
      default-zone: http://localhost:8761/eureka
    prefer-ip-address: true
    